name: Update Submodule on Release of NineChronicles

on:
  workflow_dispatch:
  repository_dispatch:
    types: [9c-release]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest submodule commit from NineChronicles
      id: get-commit
      run: |
        COMMIT_SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/planetarium/NineChronicles/git/trees/main?recursive=1 )
        echo "$COMMIT_SHA"